config/routes.rb
SquashLeague::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :rankings, :only => [:index, :show]

  resources :results

  resources :matches

  resources :playerdivs

  resources :seasons

  resources :divisions

  devise_for :players
  resources :players, :only => [:show, :index]

  resources :blogs
  
  get '/rules', :to => 'pages#rules'
  get '/tables', :to => 'pages#table'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  get '/signout', :to => 'sessions#destroy'
  get '/league',  :to => 'pages#league'
  get '/results', :to => 'pages#results'
  get '/rank', :to => 'pages#rankings'
  get '/about',    :to => 'pages#about'
  get '/emails', :to => 'pages#emails'
  

  root :to => 'blogs#index'

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
 # attr_accessible :match_id, :player_id, :score
  belongs_to :player
  belongs_to :match
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  # GET /rankings
  # GET /rankings.json
  def index
    @rankings = Ranking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rankings }
    end
  end

  # GET /rankings/1
  # GET /rankings/1.json
  def show
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ranking }
    end
  end

  # GET /rankings/new
  # GET /rankings/new.json
  def new
    @ranking = Ranking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ranking }
    end
  end

  # GET /rankings/1/edit
  def edit
    @ranking = Ranking.find(params[:id])
  end

  # POST /rankings
  # POST /rankings.json
  def create
    @ranking = Ranking.new(params[:ranking])

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, :notice => 'Ranking was successfully created.' }
        format.json { render :json => @ranking, :status => :created, :location => @ranking }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rankings/1
  # PUT /rankings/1.json
  def update
    @ranking = Ranking.find(params[:id])

    respond_to do |format|
      if @ranking.update_attributes(params[:ranking])
        format.html { redirect_to @ranking, :notice => 'Ranking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ranking.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.json
  def destroy
    @ranking = Ranking.find(params[:id])
    @ranking.destroy

    respond_to do |format|
      format.html { redirect_to rankings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rankings_helper.rb
module RankingsHelper



  def current_score(id)
    current_score = Ranking.where(:user_id => id).last.score
    return current_score
  end

  def games_played(id)
    games_played = Result.where(:user_id => id).count
    return games_played
  end

  def high_score(id)
    high_score = Ranking.where(:user_id => id).maximum("score")
    return high_score
  end

  def games_won(id)
    games_won = Result.where(:user_id => id).where(:result => 3).count
    return games_won
  end



end

app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :match_id %><br />
    <%= f.number_field :match_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Player</th>
    <th>Match</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rankings.each do |ranking| %>
  <tr>
    <td><%= ranking.score %></td>
    <td><%= ranking.player_id %></td>
    <td><%= ranking.match_id %></td>
    <td><%= link_to 'Show', ranking %></td>
    <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
    <td><%= link_to 'Destroy', ranking, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @ranking.score %>
</p>

<p>
  <b>Player:</b>
  <%= @ranking.player_id %>
</p>

<p>
  <b>Match:</b>
  <%= @ranking.match_id %>
</p>


<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>