config/routes.rb
SquashLeague::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :rankings, :only => [:index, :show]

  resources :results

  resources :matches

  resources :playerdivs

  resources :seasons

  resources :divisions

  devise_for :players
  resources :players, :only => [:show, :index]

  resources :blogs
  
  get '/rules', :to => 'pages#rules'
  get '/tables', :to => 'pages#table'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  get '/signout', :to => 'sessions#destroy'
  get '/league',  :to => 'pages#league'
  get '/results', :to => 'pages#results'
  get '/rank', :to => 'pages#rankings'
  get '/about',    :to => 'pages#about'
  get '/emails', :to => 'pages#emails'
  

  root :to => 'blogs#index'

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :player
  belongs_to :match, :inverse_of => :results
  validates_presence_of :score, :message=>"Not a valid score"
 # attr_accessible :active, :match_id, :points, :result, :score, :player_id
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, :notice => 'Result was successfully created.' }
        format.json { render :json => @result, :status => :created, :location => @result }
      else
        format.html { render :action => "new" }
        format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, :notice => 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @result.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :match_id %><br />
    <%= f.number_field :match_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :result %><br />
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.text_field :active %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Match</th>
    <th>User</th>
    <th>Score</th>
    <th>Result</th>
    <th>Active</th>
    <th>Points</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.match_id %></td>
    <td><%= result.player_id %></td>
    <td><%= result.score %></td>
    <td><%= result.result %></td>
    <td><%= result.active %></td>
    <td><%= result.points %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Match:</b>
  <%= @result.match_id %>
</p>

<p>
  <b>User:</b>
  <%= @result.player_id %>
</p>

<p>
  <b>Score:</b>
  <%= @result.score %>
</p>

<p>
  <b>Result:</b>
  <%= @result.result %>
</p>

<p>
  <b>Active:</b>
  <%= @result.active %>
</p>

<p>
  <b>Points:</b>
  <%= @result.points %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>