config/routes.rb
SquashLeague::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :rankings, :only => [:index, :show]

  resources :results

  resources :matches

  resources :playerdivs

  resources :seasons

  resources :divisions

  devise_for :players
  resources :players, :only => [:show, :index]

  resources :blogs
  
  get '/rules', :to => 'pages#rules'
  get '/tables', :to => 'pages#table'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  get '/signout', :to => 'sessions#destroy'
  get '/league',  :to => 'pages#league'
  get '/results', :to => 'pages#results'
  get '/rank', :to => 'pages#rankings'
  get '/about',    :to => 'pages#about'
  get '/emails', :to => 'pages#emails'
  

  root :to => 'blogs#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
#  attr_accessible :division_id, :rankings_attributes, :results_attributes
  has_many :results, :dependent => :delete_all, :inverse_of => :match
  has_many :rankings, :dependent => :delete_all
  #belongs_to :playerdiv
  belongs_to :division
  accepts_nested_attributes_for :rankings, :results, :reject_if => proc {|attributes| attributes.all? {|k,v| v.nil?}}
  
  
  #, :reject_if => proc { |attributes| attributes['score'].blank? }
  
  def score_empty(attributed)
    attributed['score'].blank?
  end
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include MatchesHelper
  # GET /matches
  # GET /matches.xml
  def index
    @matches = Match.page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @matches }
    end


  end
  def match_result_a(id)
    @result = Result.where(:match_id => id)
  end

  # GET /matches/1
  # GET /matches/1.xml
  def show
    @match = Match.find(params[:id])
    @result = Result.where(:match_id => params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @match }
    end
  end


  # GET /matches/new
  # GET /matches/new.xml
  def new   
    @unplayed = unplayed_playerdiv_players(get_playerdiv().division_id,current_player.id) # Get the unplayed players from current division.
    
    @players = 
    @match = Match.new
    1.times { @match.results.build }
    1.times { @match.rankings.build }
  
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    @result = Result.where(:match_id => params[:id])
    0.times { @match.results.build }
  end

  # POST /matches
  # POST /matches.xml
  def create    

    @unplayed = unplayed_playerdiv_players(get_playerdiv().division_id,current_player.id)
    #We need to edit the params here a bit!
    #Fix players 2s elo player_id, easypeasy.
    params['match']['rankings_attributes']['1']['player_id'] = params['match']['results_attributes']['1']['player_id']
    player1 = params['match']['results_attributes']['0']['player_id']
    player2 = params['match']['results_attributes']['1']['player_id']
    player1_score = params['match']['results_attributes']['0']['score']
    player2_score = params['match']['results_attributes']['1']['score']

    #Add new elo scores 
    if params['match']['results_attributes']['0']['score'] > params['match']['results_attributes']['1']['score']
      elo_scores = update_elo_score(params['match']['results_attributes']['0']['player_id'],params['match']['results_attributes']['1']['player_id']) 
      params['match']['rankings_attributes']['0']['score'] = elo_scores.first     
      params['match']['rankings_attributes']['1']['score'] = elo_scores.last
    elsif params['match']['results_attributes']['0']['score'] < params['match']['results_attributes']['1']['score']
      elo_scores = update_elo_score(params['match']['results_attributes']['1']['player_id'],params['match']['results_attributes']['0']['player_id']) 
      params['match']['rankings_attributes']['1']['score'] = elo_scores.first     
      params['match']['rankings_attributes']['0']['score'] = elo_scores.last
    elsif
      elo_scores = dont_update_elo_score(params['match']['results_attributes']['0']['player_id'],params['match']['results_attributes']['1']['player_id']) 
      params['match']['rankings_attributes']['0']['score'] = elo_scores.first     
      params['match']['rankings_attributes']['1']['score'] = elo_scores.last      
    end

    ## We want to break out and return to the new match page with a warning if the score is 3-3.
    if player1_score == "3" && player2_score == "3"
      respond_to do |format|
        format.html { redirect_to new_match_path, :alert => '3-3 is not a valid score' }
      end
    #  format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
    else      
      @match = Match.new(match_params)
      respond_to do |format|
       if @match.save
         if Rails.env.production?
           player1_info = Player.find(player1)
           if player1_info.twitter.blank?
             player1_name = player1_info.name
           else 
             if player1_info.twitter.include? "@"
                player1_name = player1_info.twitter
              else 
                player1_name = ["@",player1_info.twitter].join("")
              end
           end

           player2_info = Player.find(player2)
           if player2_info.twitter.blank?
             player2_name = player2_info.name
           else 
             if player2_info.twitter.include? "@"
               player2_name = player2_info.twitter
             else 
               player2_name = ["@",player2_info.twitter].join("")
             end
           end
        end
        ## Messaging: sending tweets and emails.
        if Rails.env.production?  
           ResultMailer.result_email(params['match']['rankings_attributes']['0']['player_id'],params['match']['rankings_attributes']['1']['player_id'],params['match']['results_attributes']['0']['score'],params['match']['results_attributes']['1']['score']).deliver
        end
        
        
        
        format.html { redirect_to(@match, :notice => "Your match has been entered successfully") }
        format.xml  { render :xml => @match, :status => :created, :location => @match }      
      else
        format.html { redirect_to new_match_path, :alert => 'You did not enter any scores' }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end
end

  # PUT /matches/1
  # PUT /matches/1.xml
  def update
    @match = Match.find(params[:id])
    @result = Result.where(:match_id => params[:id])
    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to(@match, :notice => 'Match was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.xml
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to(root_to) }
      format.xml  { head :ok }
    end
  end

  private

  def match_params
    params.require(:match).permit(:division_id, results_attributes: [:player_id, :score, :active], rankings_attributes: [:score, :player_id, :match_id])
  end

end

app/helpers/matches_helper.rb
module MatchesHelper

  # Get current playerdiv by id
  def get_playerdiv()
    playerdiv = Playerdiv.where(:player_id => current_player).last
    return playerdiv
  end




end

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<!-- Get the division_id for current logged in player -->
  	<% current_playerdiv = get_playerdiv %>
    <%= f.hidden_field :division_id, :value => current_playerdiv.division_id %><br />
	
	<!-- The controller makes this happen twice -->
	<%= f.fields_for :results do |result_form| %>

	<!-- Get the player -->
	<%= result_form.label current_player.name %>&nbsp;
	<%= result_form.hidden_field :player_id, :value => current_player.id %>
		
		<%= result_form.select :score, options_for_select([["Game Score", ""], ["0", "0"], ["1", "1"], ["2", "2"], ["3", "3"],["W/O","-1"]]) %><br />

		<%= result_form.hidden_field :active, :value => 1 %>
	<% end %>
	<!-- Rankings for player1 -->
	<%= f.fields_for :rankings do |ranking_form| %>
		<% if Ranking.where(:player_id => current_player.id).last.blank? %>
			<%= ranking_form.hidden_field :score, :value => 1000 %><br />
		<% else %>
			<%= ranking_form.hidden_field :score, :value => Ranking.where(:player_id => current_player.id).last.score %><br />
		<% end %>
		<%= ranking_form.hidden_field :player_id, :value => current_player.id %>
		<%= ranking_form.hidden_field :match_id, :value => :match_id %>
	<% end %>
	vs<br /><br />

	<!-- Get player 2 -->
		<%= f.fields_for :results do |result_form| %>

 
		<%= result_form.select :player_id, options_for_select(@unplayed) %>

 	<!-- Get the score -->

		<%= result_form.select :score, options_for_select([["Game Score", ""], ["0", "0"], ["1", "1"], ["2", "2"], ["3", "3"],["W/O","-1"]]) %><br />

		<%= result_form.hidden_field :active, :value => 1 %>
	<% end %>
	<!-- Ranking points for player 2 -->
	<%= f.fields_for :rankings do |ranking_form| %>
		
		<%= ranking_form.hidden_field :score %><br />
		<%= ranking_form.hidden_field :player_id, :value => :player_id %>
		<%= ranking_form.hidden_field :match_id, :value => :match_id %>

	<% end %>

		


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table class=>
  <tr>
    <th>Division</th>
    <th>Player 1</th>
    <th>Score</th>
    <th>Player 2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>

      <% result = match_result_a(match.id) %>
  <tr>
    <td><%= match.division_id %></td>
    <td><%= Player.find(result[0].player_id).name %></td>
    <td><%= result[0].score %> - <%= result[1].score %></td>
    <td><%= Player.find(result[1].player_id).name %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= paginate @matches %>
<br />
<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>
<p id="notice"><%= notice %></p>
<%
# Get current playerdiv by id
def get_playerdiv()
  playerdiv = Playerdiv.where(:player_id => current_player).last
  return playerdiv
end
%>

<p>In case of a walkover give the player who couldn't make it 'W/O' and yourself 3.</p>

<p>Please press submit just once</p>
<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>
  <b>Playerdiv:</b>
  <%# @match.playerdiv_id %>
</p>
-->
<%= link_to 'Profile Page', player_path(current_player) %>
<%# link_to 'Edit', edit_match_path(@match) %> |
<%# link_to 'Back', matches_path %>