config/routes.rb
SquashLeague::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :rankings, :only => [:index, :show]

  resources :results

  resources :matches

  resources :playerdivs

  resources :seasons

  resources :divisions

  devise_for :players
  resources :players, :only => [:show, :index]

  resources :blogs
  
  get '/rules', :to => 'pages#rules'
  get '/tables', :to => 'pages#table'
  get '/contact', :to => 'pages#contact'
  get '/about',   :to => 'pages#about'
  get '/help',    :to => 'pages#help'
  get '/signout', :to => 'sessions#destroy'
  get '/league',  :to => 'pages#league'
  get '/results', :to => 'pages#results'
  get '/rank', :to => 'pages#rankings'
  get '/about',    :to => 'pages#about'
  get '/emails', :to => 'pages#emails'
  

  root :to => 'blogs#index'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
 
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wimbledon Squash</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag('default', :media => :screen) %>
  <%= stylesheet_link_tag('print', :media => :print) %>
  <%= javascript_include_tag 'jquery' %>
  <%= javascript_include_tag 'bootstrap' %>
  <%= csrf_meta_tags %>
  <% if Rails.env == 'production' %>
      <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-20394306-2']);
          _gaq.push(['_trackPageview']);

          (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

      </script>
   <% end %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <span class="brand-large" href="#">Wimbledon Squash</span>

      <div class="nav-collapse">
        <ul class="nav nav-pills">
          <li><%= link_to "Home", root_path %></li>
          <li class="dropdown-toggle" data-toggle="dropdown"><a>Leagues <b class="caret"></b></a></li>
          <ul class="dropdown-menu">
            <li><a tabindex="-1" href="/league">Page 1</a></li>
            <li><a tabindex="-1" href="/league?page=2">Page 2</a></li>
            <li><a tabindex="-1" href="/league?page=3">Page 3</a></li>
            <li><a tabindex="-1" href="/league?page=4">Page 4</a></li>
            <li><a tabindex="-1" href="/league?page=5">Page 5</a></li>
            <li><a tabindex="-1" href="/league?page=6">Page 6</a></li>
          </ul>
          </a>
          
          <li><%= link_to "Contact", contact_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Players", players_path %></li>
              <li><%= link_to "Rules", rules_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to current_player.email, current_player %></li>
              <li><%= link_to "Sign out", destroy_player_session_path, :method => :delete %></li>
          <% else %>
              <li><%= link_to "Sign in", new_player_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span8">

      <div class="content">

        <section class="round">
          <% flash.each do |key, value| %>
              <div class="flash <%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
      </div>

    </div>


    <div class="span4 sidebar">
      <div class="patch round visible-desktop visible-tablet">
        <span class="patch_header">Latest Results</span><br>
        <table class="table table-striped" border="0">
          <%
             m = Match.all.last(5)
             m.each do |match|
               j = match.id
               r = Result.where(:match_id => j)
               if (r[0][:score] != -1) and (r[1][:score] != -1) %>
                  <tr class="patch_style">
                    <td align="left"><%= player_by_id(r[0][:player_id]).name %></td>
                    <td align="left"><%= r[0][:score] %></td>
                    <td align="left"> -</td>
                    <td><%= r[1][:score] %></td>
                    <td><%= player_by_id(r[1][:player_id]).name %></td>
                  </tr>
              <% end
                 end %>
        </table>
      </div>

      <% if Rails.env.production? %>
          <div class="patch round hidden-phone">
            <span class="patch_header">Team Matches</span><br>

            <iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=200&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=nickwales.co.uk_fflcvb8r0ojnnkfhoi8h1u2qfo%40group.calendar.google.com&amp;color=%23691426&amp;ctz=Europe%2FLondon" style="border-width:0" width="300" height="200" frameborder="0" scrolling="no"></iframe>

          </div>
      <% end %>

      <div class="patch round hidden-phone">
        <span class="patch_header">Links</span><br>
        <a class="patch_style" href="http://bookings.wimbledonclub.co.uk/Web/Login.aspx">Book a court</a><br/>
        <a class="patch_style" href="http://county.leaguemaster.co.uk/">Surrey Cup</a><br/>
        <a class="patch_style" href="http://www.surreysra.co.uk/">Surrey SRA</a><br/>
        <a class="patch_style" href="http://www.squashsite.co.uk/">Squashsite</a><br/><br/>
      </div>
    </div>
  </div>
</div>
</body>
</html>